# Generated by Django 4.0.7 on 2022-08-16 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notemakerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collections',
            new_name='Collection',
        ),
    ]
