# Generated by Django 4.0.7 on 2022-08-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notemakerapp', '0002_rename_collections_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='text',
            field=models.TextField(default='', max_length=150),
        ),
    ]
